name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  prepare:
    name: Prepare

    runs-on: ubuntu-latest

    outputs:
      architectures: ${{ steps.info.outputs.architectures }}
      build_matrix: ${{ steps.matrix.outputs.matrix }}
      image_name: ${{ steps.normalize.outputs.image_name }}
      name: ${{ steps.normalize.outputs.name }}
      description: ${{ steps.normalize.outputs.description }}
      url: ${{ steps.normalize.outputs.url }}
      registry_prefix: ${{ steps.normalize.outputs.registry_prefix }}
      version: ${{ steps.normalize.outputs.version }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v6

      - name: Get app information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: ./prometheus_node_exporter

      - name: Normalize app information
        id: normalize
        run: |
          image=${{ steps.info.outputs.image }}
          echo "image_name=${image##*/}" >> "$GITHUB_OUTPUT"
          echo "registry_prefix=${image%/*}" >> "$GITHUB_OUTPUT"
          version=${{ steps.info.outputs.version }}
          echo "version=${version}" >> "$GITHUB_OUTPUT"
          name=${{ steps.info.outputs.name }}
          echo "name=${name}" >> "$GITHUB_OUTPUT"
          description=${{ steps.info.outputs.description }}
          echo "description=${description}" >> "$GITHUB_OUTPUT"
          url=${{ steps.info.outputs.url }}
          if [[ -n "$url" && "$url" != "null" ]]; then
            echo "url=${url}" >> "$GITHUB_OUTPUT"
          fi

      - name: Prepare build matrix
        id: matrix
        uses: home-assistant/builder/actions/prepare-multi-arch-matrix@2026.03.2
        with:
          architectures: ${{ steps.info.outputs.architectures }}
          image-name: ${{ steps.normalize.outputs.image_name }}
          registry-prefix: ${{ steps.normalize.outputs.registry_prefix }}