name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "3 5 * * 0"

jobs:
  find:
    name: Find add-ons

    runs-on: ubuntu-latest

    outputs:
      addons: ${{ steps.addons.outputs.addons_list }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Find add-on directories
        id: addons
        uses: home-assistant/actions/helpers/find-addons@e3fb68ebda13d88a0d695082f471ba2c83d025fb # master

  lint:
    name: Lint add-on ${{ matrix.path }}

    needs: find
    runs-on: ubuntu-latest

    strategy:
      matrix:
        path: ${{ fromJson(needs.find.outputs.addons) }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Run Home Assistant Add-on Lint
        uses: frenck/action-addon-linter@f995494fd84fae6310d23617e66d0e37de4f14eb # v2
        with:
          path: "./${{ matrix.path }}"