---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  find:
    name: Find add-ons

    runs-on: ubuntu-latest

    outputs:
      addons: ${{ steps.addons.outputs.addons_list }}

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v5

      - name: Find add-on directories
        id: addons
        uses: home-assistant/actions/helpers/find-addons@master

  lint:
    name: Lint add-on ${{ matrix.path }}

    needs: find
    runs-on: ubuntu-latest

    strategy:
      matrix:
        path: ${{ fromJson(needs.find.outputs.addons) }}

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v5

      - name: Run Home Assistant Add-on Lint
        uses: frenck/action-addon-linter@v2
        with:
          path: "./${{ matrix.path }}"
          community: false
