name: "Publish Prometheus Node Exporter"

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    name: Publish Prometheus Node Exporter Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Version
        id: check
        uses: ./.github/actions/check-ghcr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: loganmarchione/hassos-addons/prometheusnodeexporter-aarch64
          configpath: prometheus_node_exporter/config.json
      - name: Publish
        if: ${{ steps.check.outputs.status == '404' }}
        uses: home-assistant/builder@master
        with:
          args: |
            --aarch64 --amd64 --armv7 \
            --target prometheus_node_exporter \
            --docker-hub ghcr.io/loganmarchione/hassos-addons \
            --image prometheusnodeexporter-{arch}
